package principal;

//public class DemoLogs {
// private static final String TAG = "MAIN";
//private static final Logger log = LogManager.getLogger(TAG);

//public static void main(String[] args) {
//   log.debug("testeando los debug");
//  log.info("testeando los info");
//    }
//}


/*
LOGS SIRVEN PARA MOSTRAR INFORMACION DE EJECUCION DEL PROYECTO

COMPOSICION DE LOGS

1. FECHA Y HORA
2. NIVEL DE LOG
3. TAG QUE AGRUPA MENSAJES DE UN MISMO TIPO DE LOG
4. MENSAJE

EJEMPLO: 2021-08-25 12:00:00 INFO AUTOMATION - HOLA SOY UN MENSAJE DE PRUEBA INFO

NIVELES DE LOGS

TRACE = TODA INFORMACION QUE SE QUIERE MOSTRAR, ES EL MAS DETALLADO
DEBUG = INFORMACION DE DEBUGGING, ES DECIR, INFORMACION QUE SE QUIERE MOSTRAR PARA DEBUGEAR, NO SON DE ALTO NIVEL
INFO = INFORMACION DE EJECUCION, ES DECIR, INFORMACION QUE SE QUIERE MOSTRAR PARA SABER QUE ESTA PASANDO, DE ALTO NIVEL
WARN = INFORMACION DE ADVERTENCIA, ES DECIR, INFORMACION QUE SE QUIERE MOSTRAR PARA ADVERTIR DE POTENCIALES ERRORES
ERROR = INFORMACION DE ERROR, ES DECIR, INFORMACION QUE SE QUIERE MOSTRAR PARA MOSTRAR ERRORER, USADO EN TRY CATCHS
FATAL = INFORMACION DE ERROR CRITICO, ES DECIR, INFORMACION QUE SE QUIERE MOSTRAR PARA MOSTRAR ERRORER CRITICOS

SU VISIBILIDAD ES DE MENOR A MAYOR, ES DECIR, SI YO PONGO INFO, SE MOSTRARAN TODOS LOS LOGS DE INFO PARA ARRIBA, SI PONGO ERROR, SE MOSTRARAN TODOS LOS LOGS DE ERROR PARA ARRIBA



 */